<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IND-PF1NGPX0" failures="1" tests="4" name="Org.testrunner.TestRunner" time="90.420" errors="0" timestamp="2024-03-16T13:31:07 IST" skipped="0">
  <testcase classname="Org.testrunner.TestRunner" name="runScenario" time="17.852"/>
  <testcase classname="Org.testrunner.TestRunner" name="runScenario" time="24.016"/>
  <testcase classname="Org.testrunner.TestRunner" name="runScenario" time="20.341"/>
  <testcase classname="Org.testrunner.TestRunner" name="runScenario" time="28.211">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Org.StepDefs.DemoPageSteps.demo_on_failed_step(DemoPageSteps.java:26)
at âœ½.Demo on failed step(file:///C:/Users/gowtham.teja/eclipse-workspace/CucumberSelenium/src/test/resources/features/DemoFile.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Org.testrunner.TestRunner -->
